### ISSUE TITLE
Request: Add reference to Matebook-X-Pro-2018 Repository

### ISSUE THREAD

**Issue by profzei** [itsabhishekolkha/Mi-notebook-14-Hackintosh#3]
Hi guys, thank you for contributing to the Mi-Notebook hackintosh community.

I notice that in your homepage, there are **too many similar parts** (**entire paragraphs!**) as [profzei's Matebook-X-Pro-2018 repo](https://github.com/profzei/Matebook-X-Pro-2018). **The LICENSE for my repo is Apache-2.0** so it would be very nice if you guys can put **at least** [profzei's Matebook-X-Pro-2018 repo](https://github.com/profzei/Matebook-X-Pro-2018) in the credits at [Readme.md](https://github.com/itsabhishekolkha/Mi-notebook-14-Hackintosh/blob/main/README.md).

Have a great day and keep going!✊✊

**Comment by itsabhishekolkha** [comment]
Thanks for letting me know brother. I just updated my REDME.md with credits.
