### ISSUE TITLE
USB Ports not working as intended 

### ISSUE THREAD

**Issue by TonyPSR** [itsabhishekolkha/Mi-notebook-14-Hackintosh#5]
You have forgot to set XhciPortLimit to False(0). This causes, my USB 3.1 ports to not work. Sometimes, even the camera and webcam doesn't work as intended.

**To Reproduce**
1. Connect USB 2.0/3.0/3.1 device on the USB 3.1 ports (left side 2 ports on non-horizon model)

**Expected behavior**
Drive icon visible on desktop and finder.

**Actual behavior**
No response from macOS.

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - OC: 0.6.9

Laptop: Mi Notebook 14 [Non-Horizon edition] 
Intel Core i5 10210U
Intel UHD for 10th gen
8GB DRR4 RAM
256GB SATA SSD
No Nvidia dGPU

**Potential fix**
Set XhciPortLimit to false in config.plist file.

Other than this issue, most of the stuff works well. Good effort.

**Comment by itsabhishekolkha** [comment]
Hi TonyPSR, thank you for contributing to the Mi-Notebook 14 Hackintosh community.

I noticed that after updating to macOS version 11.3.1 your USB mapping will not work as intended but i was not aware of this issue.
 
**Fixing**
 To fix this problem we don't need to set XhciPortLimit to false in `config.plist` file, that's because i'm not using `USBinjectAll.kext` at all. I'm using my own `USBMapping.kext` as you can see in `**EFI->OC->Kext**` folder.

**Note**- After remapping of ports I will update the **EFI** soon.

**Comment by TonyPSR** [comment]
But, I'm using the USBMap.kext with XhciPortLimit set to false. Everything is working flawlessly. From the online resources I found out after remapping the ports, XhciPortLimit must be set to false. Correct me if if I'm wrong.

By the way, thanks for the speed response.

**Comment by itsabhishekolkha** [comment]
You are right, but if we use `UsbInjectAll.kext` and `SATA-Unsupported.kext` then we need to set XhciPortLimit to false if But if we are using `USBMap.Kext`(which isn't a part of UsbInjectAll) then we don't need to set limit to false.

By the way, Now EFI is updated with new USBMap.kext and Sound system. For more details you can check the REDME.ME

**Comment by itsabhishekolkha** [comment]
One more thing, now for your peace of mind... remove the old `USBMap.kext` and update with the latest one and keep the XhciPortLimit to true or yes in **kernel->Quirks->XhciPortLimit**

**Comment by TonyPSR** [comment]
Bro, to update from 0.6.9 to 0.7.0, just changing the EFi is enough, right? Or should I make any other changes.

One more doubt, combo-jack works well. But, headphone stops working or make static distortion noise sometimes. Is it common or just happening to me?

I'll close the thread after your reply. Thanks a lot for creating such amazing EFI. Works flawlessly in terms of performance and battery life.

**Comment by itsabhishekolkha** [comment]
Just replace the **EFI** but if you have generated SMBIOS then copy your details in the new **EFI** Config.plist.
 my Combo-jack is working perfectly... try another headphones.

Thanks for the appreciation bro.
