### ISSUE TITLE
Stuck here

### ISSUE THREAD

**Issue by robdinkuiko22** [itsabhishekolkha/Mi-notebook-14-Hackintosh#9]
![IMG_20210729_121801_332.jpg](https://user-images.githubusercontent.com/69961072/127444952-a7d1b1ff-ee61-4a3e-9dca-a0e0978049ca.jpg)

**Comment by itsabhishekolkha** [comment]
it's because you are using a USB 3.0 port, use the USB 2.0 port instead.

**Comment by itsabhishekolkha** [comment]
other than that everything is fine. let me know after trying this.

**Comment by robdinkuiko22** [comment]
> it's because you are using a USB 3.0 port, use the USB 2.0 port instead.

Oh 🤯

**Comment by robdinkuiko22** [comment]
> other than that everything is fine. let me know after trying this.

Same issue

**Comment by itsabhishekolkha** [comment]
Wait for some time

**Comment by robdinkuiko22** [comment]
> It will take some time for the next step. Just wait

Same issue, tried with other ports too still doesn't work.

**Comment by itsabhishekolkha** [comment]
The installer pen drive should be in right side slot of laptop and if that doesn't work then use the OC 0.7.0 version instead of OC 0.7.1

**Comment by itsabhishekolkha** [comment]
You are the only one who is facing issue like this even I never encountered such problems... you can't install with left side ports as it will end up with HID LEGACY SHIM 2 error. 

So use right side usb port only and `reset Nvram`. Then it will it will install.

**Comment by robdinkuiko22** [comment]
> You are the only one who is facing issue like this even I never encountered such problems... you can't install with left side ports as it will end up with HID LEGACY SHIM 2 error. 
> 
> So use right side usb port only and `reset Nvram`. Then it will it will install.

It worked, thanks a lot 🤍

**Comment by itsabhishekolkha** [comment]
Enjoy!!
